### ISSUE TITLE
How to update header?

### ISSUE THREAD

**Issue by iRYO400** [florent37/HollyViewPager#7]
Hi mate! Can you help with updating header blocks, when I dynamically add a new fragment?
Smthing like in adapters
`notifyDataSetChangeg()`
especially for header
btw, awesome lib!

**Comment by iRYO400** [comment]
I mean, when I add dynamically a new Fragment, header doesn't updates, so it causes NullPointerException. Here is log

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getLeft()' on a null object reference
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator.onScroll(HollyViewPagerAnimator.java:78)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator$3.onScrollChanged(HollyViewPagerAnimator.java:151)
                                                                         at com.github.ksoichiro.android.observablescrollview.ObservableScrollView.onScrollChanged(ObservableScrollView.java:81)
                                                                         at android.view.View.scrollTo(View.java:11581)
                                                                         at android.widget.ScrollView.scrollTo(ScrollView.java:1626)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator.dispatchScroll(HollyViewPagerAnimator.java:177)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator.onScroll(HollyViewPagerAnimator.java:60)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator$3.onScrollChanged(HollyViewPagerAnimator.java:151)
                                                                         at com.github.ksoichiro.android.observablescrollview.ObservableScrollView.onScrollChanged(ObservableScrollView.java:81)
                                                                         at android.view.View.scrollTo(View.java:11581)
                                                                         at android.widget.ScrollView.scrollTo(ScrollView.java:1626)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator.dispatchScroll(HollyViewPagerAnimator.java:177)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator.onScroll(HollyViewPagerAnimator.java:60)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator$3.onScrollChanged(HollyViewPagerAnimator.java:151)
                                                                         at com.github.ksoichiro.android.observablescrollview.ObservableScrollView.onScrollChanged(ObservableScrollView.java:81)
                                                                         at android.view.View.scrollTo(View.java:11581)
                                                                         at android.widget.ScrollView.scrollTo(ScrollView.java:1626)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator.dispatchScroll(HollyViewPagerAnimator.java:177)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator.onScroll(HollyViewPagerAnimator.java:60)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator$3.onScrollChanged(HollyViewPagerAnimator.java:151)
                                                                         at com.github.ksoichiro.android.observablescrollview.ObservableScrollView.onScrollChanged(ObservableScrollView.java:81)
                                                                         at android.view.View.scrollTo(View.java:11581)
                                                                         at android.widget.ScrollView.scrollTo(ScrollView.java:1626)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator.dispatchScroll(HollyViewPagerAnimator.java:177)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator.onScroll(HollyViewPagerAnimator.java:60)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator$3.onScrollChanged(HollyViewPagerAnimator.java:151)
                                                                         at com.github.ksoichiro.android.observablescrollview.ObservableScrollView.onScrollChanged(ObservableScrollView.java:81)
                                                                         at android.view.View.scrollTo(View.java:11581)
                                                                         at android.widget.ScrollView.scrollTo(ScrollView.java:1626)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator.dispatchScroll(HollyViewPagerAnimator.java:177)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator.onScroll(HollyViewPagerAnimator.java:60)
                                                                         at com.github.florent37.hollyviewpager.HollyViewPagerAnimator$3.onScrollChanged(HollyViewPagerAnimator.java:151)
                                                                         at com.github.ksoichiro.android.observablescrollview.ObservableScrollView.onScrollChanged(ObservableScrollView.java:81)
                                                                         at android.view.View.scrollTo(View.java:11581)
                                                                         at android.widget.ScrollView.onOverScrolled(ScrollView.java:806)
                                                                         at android.view.View.overScrollBy(View.java:18697)
                                                                         at android.widget.ScrollView.onTouchEvent(ScrollView.java:666)
                                                                         at com.github.ksoichiro.android.observablescrollview.ObservableScrollView.onTouchEvent(ObservableScrollView.java:189)
                                                                         at android.view.View.dispatchTouchEvent(View.java:8547)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2400)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2093)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                        at android.view.ViewGroup.dispatchTrans
```
